### ISSUE TITLE
New syntax idea for repeating attribute values

### ISSUE THREAD

**Issue by cmachu** [sass/ruby-sass#70] opened 2018-07-16 11:47 UTC
When you need repeat same attribute values, like:
```
.red{
  color:red;
  border-color:red;

  .box{
    width:100px;
    height:100px;
  }

}
```

maybe easier syntax will be:
```
.red{
  color,
  border-color:red;

  .box{
    width,
    height:100px;
  }

}
```

and both samples will produce output:

```
.red {
  color: red;
  border-color: red;
}

.red .box {
  width: 100px;
  height: 100px;
}
```

**Comment by nex3** [comment] 2018-07-17 00:22
Duplicate of sass/sass#109

**Closed by nex3** 2018-07-17 00:22 UTC
